[package]
name = "sam-utils"
version = "0.17.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.30"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
dirs = "4.0.0"
